import { useState } from "react";
import { Plus, Trash2, Download, FileText } from "lucide-react";
import { useTranslation } from "react-i18next";

interface EnvVar {
  id: string;
  key: string;
  value: string;
  comment: string;
}

export default function EnvGenerator() {
  const { t } = useTranslation();
  const [variables, setVariables] = useState<EnvVar[]>([
    { id: crypto.randomUUID(), key: "", value: "", comment: "" },
  ]);

  const addVariable = () => {
    setVariables([
      ...variables,
      { id: crypto.randomUUID(), key: "", value: "", comment: "" },
    ]);
  };

  const removeVariable = (id: string) => {
    setVariables(variables.filter((v) => v.id !== id));
  };

  const updateVariable = (id: string, field: keyof EnvVar, value: string) => {
    setVariables(
      variables.map((v) => (v.id === id ? { ...v, [field]: value } : v))
    );
  };

  const generateEnvFile = () => {
    let content = "# Environment Variables\n# Generated by The Transformer\n\n";

    variables.forEach((v) => {
      if (v.key.trim()) {
        if (v.comment.trim()) {
          content += `# ${v.comment}\n`;
        }
        content += `${v.key}=${v.value}\n\n`;
      }
    });

    return content;
  };

  const downloadEnv = () => {
    const content = generateEnvFile();
    const blob = new Blob([content], { type: "text/plain" });
    const url = URL.createObjectURL(blob);
    const a = document.createElement("a");
    a.href = url;
    a.download = ".env";
    a.click();
    URL.revokeObjectURL(url);
  };

  const applyTemplate = (template: string) => {
    let newVars: Omit<EnvVar, "id">[] = [];

    switch (template) {
      case "node":
        newVars = [
          {
            key: "NODE_ENV",
            value: "development",
            comment: t("dev.env.vars.nodeEnv"),
          },
          { key: "PORT", value: "3000", comment: t("dev.env.vars.port") },
          {
            key: "DATABASE_URL",
            value: "",
            comment: t("dev.env.vars.dbUrl"),
          },
          {
            key: "JWT_SECRET",
            value: "",
            comment: t("dev.env.vars.jwtSecret"),
          },
        ];
        break;
      case "react":
        newVars = [
          {
            key: "REACT_APP_API_URL",
            value: "",
            comment: t("dev.env.vars.apiUrl"),
          },
          {
            key: "REACT_APP_ENV",
            value: "development",
            comment: t("dev.env.vars.env"),
          },
        ];
        break;
      case "nextjs":
        newVars = [
          {
            key: "NEXT_PUBLIC_API_URL",
            value: "",
            comment: t("dev.env.vars.publicApiUrl"),
          },
          { key: "DATABASE_URL", value: "", comment: t("dev.env.vars.dbUrl") },
          {
            key: "NEXTAUTH_SECRET",
            value: "",
            comment: t("dev.env.vars.nextAuthSecret"),
          },
          {
            key: "NEXTAUTH_URL",
            value: "http://localhost:3000",
            comment: t("dev.env.vars.nextAuthUrl"),
          },
        ];
        break;
    }

    setVariables(newVars.map((v) => ({ ...v, id: crypto.randomUUID() })));
  };

  return (
    <div className="max-w-6xl mx-auto h-[calc(100vh-8rem)] flex flex-col gap-6 animate-in fade-in duration-500 pb-24">
      <header className="space-y-2">
        <h1 className="text-3xl font-bold text-gray-900 dark:text-gray-100 flex items-center gap-3">
          <div className="p-2 bg-teal-600 rounded-lg shadow-lg shadow-teal-500/20">
            <FileText className="w-6 h-6 text-white" />
          </div>
          {t("dev.env.title")}
        </h1>
        <p className="text-gray-600 dark:text-gray-400">
          {t("dev.env.description")}
        </p>
      </header>

      {/* Templates */}
      <div className="bg-white dark:bg-gray-800 rounded-xl p-4 border border-gray-200 dark:border-gray-700 shadow-sm">
        <h3 className="text-sm font-semibold text-gray-700 dark:text-gray-300 mb-3">
          {t("dev.env.templates")}
        </h3>
        <div className="flex flex-wrap gap-2">
          <button
            onClick={() => applyTemplate("node")}
            className="px-3 py-1.5 text-sm bg-green-100 dark:bg-green-900/30 hover:bg-green-200 dark:hover:bg-green-900/50 text-green-700 dark:text-green-300 rounded-lg transition-colors"
          >
            {t("dev.env.node")}
          </button>
          <button
            onClick={() => applyTemplate("react")}
            className="px-3 py-1.5 text-sm bg-blue-100 dark:bg-blue-900/30 hover:bg-blue-200 dark:hover:bg-blue-900/50 text-blue-700 dark:text-blue-300 rounded-lg transition-colors"
          >
            {t("dev.env.react")}
          </button>
          <button
            onClick={() => applyTemplate("nextjs")}
            className="px-3 py-1.5 text-sm bg-purple-100 dark:bg-purple-900/30 hover:bg-purple-200 dark:hover:bg-purple-900/50 text-purple-700 dark:text-purple-300 rounded-lg transition-colors"
          >
            {t("dev.env.nextjs")}
          </button>
        </div>
      </div>

      {/* Variables */}
      <div className="flex-1 bg-white dark:bg-gray-800 rounded-xl p-6 border border-gray-200 dark:border-gray-700 shadow-sm overflow-y-auto space-y-3">
        {variables.map((v) => (
          <div
            key={v.id}
            className="flex gap-3 items-start p-4 bg-gray-50 dark:bg-gray-900/50 rounded-lg"
          >
            <div className="flex-1 grid grid-cols-1 md:grid-cols-3 gap-3">
              <input
                type="text"
                value={v.key}
                onChange={(e) => updateVariable(v.id, "key", e.target.value)}
                placeholder={t("dev.env.key")}
                className="px-3 py-2 rounded-lg border border-gray-200 dark:border-gray-700 bg-white dark:bg-gray-900 font-mono text-sm uppercase focus:ring-2 focus:ring-teal-500 focus:border-transparent outline-none"
              />
              <input
                type="text"
                value={v.value}
                onChange={(e) => updateVariable(v.id, "value", e.target.value)}
                placeholder={t("dev.env.value")}
                className="px-3 py-2 rounded-lg border border-gray-200 dark:border-gray-700 bg-white dark:bg-gray-900 font-mono text-sm focus:ring-2 focus:ring-teal-500 focus:border-transparent outline-none"
              />
              <input
                type="text"
                value={v.comment}
                onChange={(e) =>
                  updateVariable(v.id, "comment", e.target.value)
                }
                placeholder={t("dev.env.comment")}
                className="px-3 py-2 rounded-lg border border-gray-200 dark:border-gray-700 bg-white dark:bg-gray-900 text-sm focus:ring-2 focus:ring-teal-500 focus:border-transparent outline-none"
              />
            </div>
            <button
              onClick={() => removeVariable(v.id)}
              className="mt-1 p-2 text-gray-400 hover:text-red-600 dark:hover:text-red-400 transition-colors"
              disabled={variables.length === 1}
            >
              <Trash2 className="w-4 h-4" />
            </button>
          </div>
        ))}

        <button
          onClick={addVariable}
          className="w-full py-3 border-2 border-dashed border-gray-300 dark:border-gray-700 rounded-lg text-gray-500 dark:text-gray-400 hover:border-teal-500 hover:text-teal-600 dark:hover:text-teal-400 transition-colors flex items-center justify-center gap-2"
        >
          <Plus className="w-4 h-4" /> {t("dev.env.add")}
        </button>
      </div>

      {/* Preview & Download */}
      <div className="bg-white dark:bg-gray-800 rounded-xl p-6 border border-gray-200 dark:border-gray-700 shadow-sm space-y-4">
        <div>
          <label className="block text-sm font-medium text-gray-700 dark:text-gray-300 mb-2">
            {t("dev.env.preview")}
          </label>
          <pre className="px-4 py-3 bg-gray-900 dark:bg-black rounded-lg text-green-400 font-mono text-sm overflow-x-auto max-h-40">
            {generateEnvFile()}
          </pre>
        </div>

        <button
          onClick={downloadEnv}
          className="w-full py-3 bg-teal-600 hover:bg-teal-700 text-white rounded-xl font-medium shadow-lg shadow-teal-500/25 flex items-center justify-center gap-2 transition-colors"
        >
          <Download className="w-5 h-5" /> {t("dev.env.download")}
        </button>
      </div>
    </div>
  );
}
