import { useState } from "react";
import { Copy, Check, Download, Search, Trash2, FileCode } from "lucide-react";
import { useTranslation } from "react-i18next";

const TEMPLATES: Record<string, string> = {
  Node: "node_modules/\nnpm-debug.log*\nyarn-debug.log*\nyarn-error.log*\n.env\n.env.local\n.env.development.local\n.env.test.local\n.env.production.local\n",
  Python:
    "__pycache__/\n*.py[cod]\n*$py.class\n.env\n.venv\nenv/\nvenv/\nENV/\nenv.bak/\nvenv.bak/\n",
  Windows: "Thumbs.db\nehthumbs.db\nDesktop.ini\n$RECYCLE.BIN/\n",
  macOS:
    ".DS_Store\n.AppleDouble\n.LSOverride\nIcon\r\n._*\n.Spotlight-V100\n.Trashes\n",
  VisualStudioCode:
    ".vscode/\n!.vscode/settings.json\n!.vscode/tasks.json\n!.vscode/launch.json\n!.vscode/extensions.json\n*.code-workspace\n",
  React:
    "build/\ndist/\n.env.local\n.env.development.local\n.env.test.local\n.env.production.local\n",
  Vue: "dist/\n.env.local\n",
  Docker: ".dockerignore\n",
  JetBrains: ".idea/\ncmake-build-*/\n*.iws\nout/\n",
};

export default function GitignoreGenerator() {
  const { t } = useTranslation();
  const [selected, setSelected] = useState<string[]>([]);
  const [customIgnore, setCustomIgnore] = useState("");
  const [query, setQuery] = useState("");
  const [copied, setCopied] = useState(false);

  const filteredTemplates = Object.keys(TEMPLATES).filter((name) =>
    name.toLowerCase().includes(query.toLowerCase())
  );

  const toggleTemplate = (name: string) => {
    setSelected((prev) =>
      prev.includes(name) ? prev.filter((n) => n !== name) : [...prev, name]
    );
  };

  const getFullContent = () => {
    let content = "# Generated by The Transformer\n\n";
    selected.forEach((name) => {
      content += `### ${name} ###\n${TEMPLATES[name]}\n`;
    });
    if (customIgnore.trim()) {
      content += `### Custom ###\n${customIgnore}\n`;
    }
    return content;
  };

  const handleCopy = () => {
    navigator.clipboard.writeText(getFullContent());
    setCopied(true);
    setTimeout(() => setCopied(false), 2000);
  };

  const handleDownload = () => {
    const element = document.createElement("a");
    const file = new Blob([getFullContent()], { type: "text/plain" });
    element.href = URL.createObjectURL(file);
    element.download = ".gitignore";
    document.body.appendChild(element);
    element.click();
    document.body.removeChild(element);
  };

  return (
    <div className="max-w-6xl mx-auto space-y-8 animate-in fade-in slide-in-from-bottom-4 duration-500">
      <div className="text-center space-y-2">
        <h1 className="text-4xl md:text-5xl font-black tracking-tighter premium-gradient">
          {t("gitignore.title", ".gitignore Generator")}
        </h1>
        <p className="text-app-text-sub">
          {t(
            "gitignore.subtitle",
            "Generate professional .gitignore files for your projects"
          )}
        </p>
      </div>

      <div className="grid grid-cols-1 lg:grid-cols-12 gap-8">
        {/* Left Panel: Selection */}
        <div className="lg:col-span-4 space-y-6">
          <div className="bg-app-panel border border-app-border rounded-2xl p-6 space-y-4">
            <div className="relative">
              <Search className="absolute left-3 top-1/2 -translate-y-1/2 w-4 h-4 text-app-text-passive" />
              <input
                type="text"
                placeholder="Search templates..."
                className="w-full bg-app-bg border border-app-border rounded-xl pl-10 pr-4 py-2 text-sm focus:border-app-primary outline-none transition-all"
                value={query}
                onChange={(e) => setQuery(e.target.value)}
              />
            </div>

            <div className="flex flex-wrap gap-2 max-h-[400px] overflow-y-auto pr-2 no-scrollbar">
              {filteredTemplates.map((name) => (
                <button
                  key={name}
                  onClick={() => toggleTemplate(name)}
                  className={`px-3 py-1.5 rounded-lg text-xs font-medium border transition-all ${
                    selected.includes(name)
                      ? "bg-app-primary/20 border-app-primary text-app-primary"
                      : "bg-app-bg border-app-border text-app-text-sub hover:border-app-primary/50"
                  }`}
                >
                  {name}
                </button>
              ))}
            </div>

            {selected.length > 0 && (
              <div className="pt-4 border-t border-app-border">
                <button
                  onClick={() => setSelected([])}
                  className="flex items-center gap-2 text-xs text-red-400 hover:text-red-500 transition-colors"
                >
                  <Trash2 className="w-3 h-3" />
                  Clear Selection
                </button>
              </div>
            )}
          </div>

          <div className="bg-app-panel border border-app-border rounded-2xl p-6 space-y-4">
            <h3 className="text-sm font-bold uppercase tracking-widest text-app-text-sub">
              Custom Rules
            </h3>
            <textarea
              placeholder="Add your own rules here..."
              className="w-full h-32 bg-app-bg border border-app-border rounded-xl p-4 text-sm font-mono focus:border-app-primary outline-none transition-all resize-none"
              value={customIgnore}
              onChange={(e) => setCustomIgnore(e.target.value)}
            />
          </div>
        </div>

        {/* Right Panel: Preview */}
        <div className="lg:col-span-8 space-y-4">
          <div className="flex items-center justify-between px-2">
            <div className="flex items-center gap-2 text-app-text-sub">
              <FileCode className="w-4 h-4" />
              <span className="text-sm font-medium">Preview</span>
            </div>
            <div className="flex gap-2">
              <button
                onClick={handleCopy}
                className="flex items-center gap-2 px-4 py-2 bg-app-panel border border-app-border rounded-xl text-sm font-medium hover:border-app-primary transition-all group"
              >
                {copied ? (
                  <Check className="w-4 h-4 text-green-500" />
                ) : (
                  <Copy className="w-4 h-4 text-app-text-sub group-hover:text-app-primary" />
                )}
                {copied ? "Copied!" : "Copy"}
              </button>
              <button
                onClick={handleDownload}
                className="flex items-center gap-2 px-4 py-2 bg-app-primary text-white rounded-xl text-sm font-medium hover:bg-app-primary-hover shadow-lg shadow-app-primary/20 transition-all"
              >
                <Download className="w-4 h-4" />
                Download
              </button>
            </div>
          </div>

          <div className="bg-app-panel border border-app-border rounded-2xl overflow-hidden shadow-2xl">
            <div className="p-1 bg-app-border/30 flex items-center gap-2 px-4 h-10 border-b border-app-border">
              <div className="w-3 h-3 rounded-full bg-red-500/50" />
              <div className="w-3 h-3 rounded-full bg-yellow-500/50" />
              <div className="w-3 h-3 rounded-full bg-green-500/50" />
              <span className="ml-2 text-xs font-mono text-app-text-passive">
                .gitignore
              </span>
            </div>
            <pre className="p-6 md:p-8 text-sm font-mono text-app-text-sub overflow-auto max-h-[600px] leading-relaxed">
              {getFullContent()}
            </pre>
          </div>
        </div>
      </div>
    </div>
  );
}
