import {
  FileJson,
  Image as ImageIcon,
  FileType,
  FileCode,
  ArrowRightLeft,
  Settings,
  Activity,
  Palette,
  QrCode,
  Square,
  Binary,
  Database,
  Terminal,
  FileText,
  Lock,
  Fingerprint,
  Link as LinkIcon,
  Code2,
  Share2,
  Regex,
  Globe,
  Eraser,
  FileSpreadsheet,
  CaseUpper,
  Wand2,
  ShieldAlert,
  Clock,
  Gauge,
  Grab,
  Scissors,
  Zap,
  ShieldCheck,
  BarChart3,
  Brain,
  Workflow,
  Network,
  History,
  Repeat,
  FileSearch,
  Key,
  ShieldQuestion,
  Search,
  TrendingUp,
  Split,
  MessageSquareCode,
  Download,
  Music,
} from "lucide-react";

export const TOOLS_CONFIG = [
  {
    id: "converters",
    tools: [
      {
        id: "json-csv",
        icon: FileJson,
        path: "/json-csv",
        color: "from-orange-500 to-red-600",
      },
      {
        id: "json-ts",
        icon: FileCode,
        path: "/json-ts",
        color: "from-blue-600 to-indigo-600",
      },
      {
        id: "config",
        icon: Settings,
        path: "/config",
        color: "from-gray-600 to-slate-700",
      },
      {
        id: "xml-json",
        icon: ArrowRightLeft,
        path: "/xml-json",
        color: "from-orange-500 to-amber-600",
      },
      {
        id: "excel-csv",
        icon: FileSpreadsheet,
        path: "/excel-csv",
        color: "from-green-600 to-emerald-700",
      },
      {
        id: "curl",
        icon: Terminal,
        path: "/curl",
        color: "from-green-600 to-emerald-700",
      },
      {
        id: "dat-converter",
        icon: FileCode,
        path: "/dat-converter",
        color: "from-slate-600 to-zinc-700",
      },
    ],
  },
  {
    id: "media",
    tools: [
      {
        id: "img-conv",
        icon: ImageIcon,
        path: "/image-converter",
        color: "from-purple-500 to-pink-600",
      },
      {
        id: "img-format",
        icon: FileType,
        path: "/img-format",
        color: "from-blue-500 to-cyan-600",
      },
      {
        id: "svg",
        icon: Code2,
        path: "/svg",
        color: "from-amber-500 to-orange-600",
      },
      {
        id: "color",
        icon: Palette,
        path: "/color",
        color: "from-pink-500 to-rose-600",
      },
      {
        id: "ocr",
        icon: FileText,
        path: "/ocr",
        color: "from-neutral-600 to-neutral-800",
      },
      {
        id: "bg-remover",
        icon: Eraser,
        path: "/bg-remover",
        color: "from-purple-600 to-indigo-600",
      },
      {
        id: "compress",
        icon: Share2,
        path: "/compress",
        color: "from-pink-600 to-rose-600",
      },
      {
        id: "crop",
        icon: Eraser,
        path: "/crop",
        color: "from-teal-600 to-emerald-600",
      },
      {
        id: "img-pdf",
        icon: FileText,
        path: "/img-pdf",
        color: "from-red-600 to-rose-600",
      },
      {
        id: "pdf-img",
        icon: ImageIcon,
        path: "/pdf-img",
        color: "from-orange-600 to-amber-600",
      },
      {
        id: "exif-cleaner",
        icon: ShieldAlert,
        path: "/exif-cleaner",
        color: "from-red-500 to-pink-600",
      },
      {
        id: "pdf-tools",
        icon: FileText,
        path: "/pdf-tools",
        color: "from-red-600 to-rose-600",
      },
      {
        id: "favicon",
        icon: ImageIcon,
        path: "/favicon",
        color: "from-amber-400 to-orange-500",
      },
      {
        id: "svg-optimizer",
        icon: Zap,
        path: "/svg-optimizer",
        color: "from-yellow-500 to-amber-600",
      },
      {
        id: "media-downloader",
        icon: Download,
        path: "/media-downloader",
        color: "from-red-600 to-rose-700",
      },
      {
        id: "mp4-to-mp3",
        icon: Music,
        path: "/mp4-to-mp3",
        color: "from-purple-600 to-violet-700",
      },
      {
        id: "video-clipper",
        icon: Scissors,
        path: "/video-clipper",
        color: "from-orange-600 to-red-600",
      },
    ],
  },
  {
    id: "text",
    tools: [
      {
        id: "text-md",
        icon: FileCode,
        path: "/markdown",
        color: "from-emerald-500 to-green-600",
      },
      {
        id: "text-diff",
        icon: ArrowRightLeft,
        path: "/diff",
        color: "from-amber-500 to-yellow-600",
      },
      {
        id: "log-analyzer",
        icon: Activity,
        path: "/log-analyzer",
        color: "from-rose-500 to-red-600",
      },
      {
        id: "lorem",
        icon: FileText,
        path: "/lorem",
        color: "from-purple-500 to-indigo-600",
      },
    ],
  },
  {
    id: "developer",
    tools: [
      {
        id: "jwt",
        icon: Lock,
        path: "/jwt",
        color: "from-yellow-600 to-orange-700",
      },
      {
        id: "base64",
        icon: Binary,
        path: "/base64",
        color: "from-cyan-600 to-blue-700",
      },
      {
        id: "epoch",
        icon: Clock,
        path: "/epoch",
        color: "from-violet-600 to-purple-700",
      },
      {
        id: "json-yaml",
        icon: FileJson,
        path: "/json-yaml",
        color: "from-teal-600 to-green-700",
      },
      {
        id: "sql",
        icon: Database,
        path: "/sql",
        color: "from-blue-700 to-indigo-800",
      },
      {
        id: "metadata",
        icon: Binary,
        path: "/metadata",
        color: "from-fuchsia-600 to-purple-800",
      },
      {
        id: "seo",
        icon: Share2,
        path: "/seo",
        color: "from-indigo-600 to-cyan-600",
      },
      {
        id: "minifier",
        icon: Wand2,
        path: "/minifier",
        color: "from-cyan-600 to-sky-700",
      },
      {
        id: "validator",
        icon: FileJson,
        path: "/json-validator",
        color: "from-green-600 to-teal-700",
      },
      {
        id: "beautifier",
        icon: Wand2,
        path: "/beautifier",
        color: "from-fuchsia-600 to-pink-700",
      },
      {
        id: "text-case",
        icon: CaseUpper,
        path: "/text-case",
        color: "from-violet-600 to-indigo-700",
      },
      {
        id: "regex",
        icon: Regex,
        path: "/regex",
        color: "from-yellow-500 to-amber-600",
      },
      {
        id: "http-status",
        icon: Globe,
        path: "/http-status",
        color: "from-blue-500 to-indigo-600",
      },
      {
        id: "user-agent",
        icon: Globe,
        path: "/user-agent",
        color: "from-cyan-500 to-teal-600",
      },
      {
        id: "cron-generator",
        icon: Clock,
        path: "/cron-generator",
        color: "from-emerald-500 to-green-600",
      },
      {
        id: "env-generator",
        icon: FileText,
        path: "/env-generator",
        color: "from-slate-500 to-gray-600",
      },
      {
        id: "mock-data",
        icon: Database,
        path: "/mock-data",
        color: "from-orange-500 to-red-600",
      },
      {
        id: "chmod",
        icon: ShieldAlert,
        path: "/chmod",
        color: "from-amber-600 to-orange-700",
      },
      {
        id: "gitignore",
        icon: FileCode,
        path: "/gitignore",
        color: "from-slate-600 to-zinc-700",
      },
    ],
  },
  {
    id: "network",
    tools: [
      {
        id: "ip",
        icon: Globe,
        path: "/ip",
        color: "from-teal-500 to-cyan-600",
      },
      {
        id: "speed-test",
        icon: Gauge,
        path: "/speed-test",
        color: "from-cyan-400 to-blue-500",
      },
    ],
  },
  {
    id: "security",
    tools: [
      {
        id: "hash",
        icon: Fingerprint,
        path: "/hash",
        color: "from-slate-600 to-zinc-700",
      },
      {
        id: "uuid",
        icon: Fingerprint,
        path: "/uuid",
        color: "from-indigo-600 to-blue-700",
      },
      {
        id: "url",
        icon: LinkIcon,
        path: "/url-encode",
        color: "from-sky-600 to-cyan-700",
      },
      {
        id: "fingerprint",
        icon: Fingerprint,
        path: "/fingerprint",
        color: "from-rose-600 to-red-700",
      },
      {
        id: "password",
        icon: Lock,
        path: "/password",
        color: "from-emerald-600 to-green-700",
      },
      {
        id: "password-strength",
        icon: Lock,
        path: "/password-strength",
        color: "from-red-600 to-rose-700",
      },
      {
        id: "jwt-generator",
        icon: Lock,
        path: "/jwt-generator",
        color: "from-orange-600 to-amber-700",
      },
      {
        id: "csrf-token",
        icon: Lock,
        path: "/csrf-token",
        color: "from-blue-600 to-indigo-700",
      },
      {
        id: "secure-key",
        icon: Lock,
        path: "/secure-key",
        color: "from-purple-600 to-violet-700",
      },
      {
        id: "email-header",
        icon: Lock,
        path: "/email-header",
        color: "from-cyan-600 to-sky-700",
      },
    ],
  },
  {
    id: "visual",
    tools: [
      {
        id: "palette",
        icon: Palette,
        path: "/palette",
        color: "from-pink-500 to-rose-600",
      },
      {
        id: "mind-map",
        icon: Grab,
        path: "/mind-map",
        color: "from-blue-500 to-indigo-600",
      },
      {
        id: "qr",
        icon: QrCode,
        path: "/qr",
        color: "from-slate-700 to-gray-800",
      },
      {
        id: "box-shadow",
        icon: Square,
        path: "/box-shadow",
        color: "from-indigo-500 to-purple-600",
      },
      {
        id: "gradient",
        icon: Palette,
        path: "/gradient",
        color: "from-orange-500 to-red-600",
      },
      {
        id: "glassmorphism",
        icon: Palette,
        path: "/glassmorphism",
        color: "from-blue-500 to-cyan-600",
      },
      {
        id: "neumorphism",
        icon: Palette,
        path: "/neumorphism",
        color: "from-slate-500 to-gray-600",
      },
      {
        id: "clamp",
        icon: Code2,
        path: "/clamp",
        color: "from-green-500 to-emerald-600",
      },
      {
        id: "font-pairing",
        icon: FileText,
        path: "/font-pairing",
        color: "from-purple-500 to-violet-600",
      },
      {
        id: "clip-path",
        icon: Scissors,
        path: "/clip-path",
        color: "from-indigo-600 to-blue-700",
      },
    ],
  },
  {
    id: "seo",
    tools: [
      {
        id: "meta-tags",
        icon: Globe,
        path: "/meta-tags",
        color: "from-blue-500 to-indigo-600",
      },
      {
        id: "robots-txt",
        icon: FileText,
        path: "/robots-txt",
        color: "from-green-500 to-emerald-600",
      },
      {
        id: "sitemap",
        icon: Share2,
        path: "/sitemap",
        color: "from-orange-500 to-amber-600",
      },
      {
        id: "page-speed",
        icon: Activity,
        path: "/page-speed",
        color: "from-purple-500 to-pink-600",
      },
      {
        id: "seo-preview",
        icon: Globe,
        path: "/seo-preview",
        color: "from-cyan-500 to-sky-600",
      },
    ],
  },
  {
    id: "live",
    tools: [
      {
        id: "api-tester",
        icon: Terminal,
        path: "/api-tester",
        color: "from-blue-600 to-indigo-600",
      },
      {
        id: "webhook",
        icon: Network,
        path: "/webhook",
        color: "from-purple-600 to-pink-600",
      },
      {
        id: "http-replay",
        icon: Repeat,
        path: "/http-replay",
        color: "from-emerald-600 to-teal-600",
      },
      {
        id: "dns-ssl",
        icon: ShieldCheck,
        path: "/dns-ssl",
        color: "from-cyan-600 to-blue-700",
      },
    ],
  },
  {
    id: "security-pro",
    tools: [
      {
        id: "rate-limit",
        icon: Activity,
        path: "/rate-limit",
        color: "from-red-600 to-rose-700",
      },
      {
        id: "jwt-live",
        icon: Key,
        path: "/jwt-live",
        color: "from-amber-600 to-orange-700",
      },
      {
        id: "password-policy",
        icon: ShieldQuestion,
        path: "/password-policy",
        color: "from-slate-600 to-zinc-700",
      },
      {
        id: "csp",
        icon: FileSearch,
        path: "/csp",
        color: "from-indigo-600 to-blue-700",
      },
      {
        id: "security-headers",
        icon: ShieldCheck,
        path: "/security-headers",
        color: "from-green-600 to-teal-700",
      },
    ],
  },
  {
    id: "seo-growth",
    tools: [
      {
        id: "serp",
        icon: Search,
        path: "/serp",
        color: "from-blue-500 to-indigo-600",
      },
      {
        id: "keyword-intent",
        icon: BarChart3,
        path: "/keyword-intent",
        color: "from-purple-500 to-pink-600",
      },
      {
        id: "ab-tester",
        icon: Split,
        path: "/ab-tester",
        color: "from-orange-500 to-amber-600",
      },
      {
        id: "meta-compare",
        icon: TrendingUp,
        path: "/meta-compare",
        color: "from-cyan-500 to-sky-600",
      },
      {
        id: "backlink",
        icon: LinkIcon,
        path: "/backlink",
        color: "from-indigo-600 to-cyan-600",
      },
    ],
  },
  {
    id: "ai-tools",
    tools: [
      {
        id: "ai-error",
        icon: Brain,
        path: "/ai-error",
        color: "from-rose-600 to-pink-700",
      },
      {
        id: "ai-log",
        icon: Search,
        path: "/ai-log",
        color: "from-indigo-600 to-violet-700",
      },
      {
        id: "ai-regex",
        icon: Regex,
        path: "/ai-regex",
        color: "from-fuchsia-600 to-purple-700",
      },
      {
        id: "ai-api",
        icon: MessageSquareCode,
        path: "/ai-api",
        color: "from-emerald-600 to-teal-700",
      },
    ],
  },
  {
    id: "ecosystem",
    tools: [
      {
        id: "flow",
        icon: Workflow,
        path: "/flow",
        color: "from-blue-600 to-cyan-600",
      },
      {
        id: "history",
        icon: History,
        path: "/history",
        color: "from-slate-600 to-gray-700",
      },
    ],
  },
];

export const ALL_TOOLS = TOOLS_CONFIG.flatMap((s) => s.tools);
